/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

static void gpio_led_init(void);
static void tim_3_init(void);
int main(void)
{
    gpio_led_init();
    tim_3_init();

	while(1);
    {

    }
    return 0;
}


void TIM3_IRQHandler(void)
{
    if (TIM3->SR && TIM_SR_UIF) {
        TIM3->SR &= ~TIM_SR_UIF;          /* clear the update flag */
        GPIOA->ODR ^= (GPIO_ODR_OD5); /* toggle the LED state */
    }
}


static void gpio_led_init(void)
{
    /* Enable the clock for GPIOA */
    RCC ->AHB1ENR |= (1 << 0); // Enable GPIOA clock (bit 0 of AHB1ENR)
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN_Msk;

    /* Configure PA5 as output (LED) */
    GPIOA->MODER &= ~(0b11 << GPIO_MODER_MODE5_Pos); // Clear mode bits for PA5
    GPIOA->MODER |= (0b01 << GPIO_MODER_MODE5_Pos);  // Set PA5 to output mode
    GPIOA->OTYPER &= ~(0b1 << GPIO_OTYPER_OT5_Pos);  // Set PA5 to push-pull
    GPIOA->OSPEEDR |= (0b01 << GPIO_OSPEEDR_OSPEED5_Pos); // Set PA5 to medium speed
    GPIOA->PUPDR &= ~(0b11 << GPIO_PUPDR_PUPD5_Pos); // No pull-up, no pull-down    
    GPIOA->ODR |= (0b1 << GPIO_ODR_OD5_Pos); // Set PA5 high (turn on LED)
}

static void tim_3_init(void)
{
    /* Enable the clock for TIM3 */
    RCC->APB1ENR |= RCC_APB1ENR_TIM3EN_Msk; // Enable TIM3 clock

    /* Configure TIM3 */
    TIM3->CNT = (0); // Reset the counter
    TIM3->PSC = (1000 - 1); // Set prescaler to 1000 incrementing every 1ms
    TIM3->ARR = (2500 - 1); // Set auto-reload value to 2500 for a 2.5s period


    TIM3->CR1 &= ~(0b11 << TIM_CR1_CEN_Pos); // Disable TIM3
    TIM3->CR1 |= 0b01 << TIM_CR1_ARPE; // Enable auto-reload preload
    TIM3->CR1 &= ~(TIM_CR1_DIR_Pos); // Set counter direction to upcounting

    TIM3->DIER |= TIM_DIER_UIE; // Enable update interrupt
    NVIC_EnableIRQ(TIM3_IRQn); // Enable TIM3 interrupt in NVIC
    
    TIM3->CR1 |= TIM_CR1_CEN; // Enable TIM3
}